; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ================= Pico 2 W ==================
; =============================================
; Production (release)
; =============================================
[env:rpipico2w]
extends = env:base
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200
upload_protocol = picotool
build_flags = 
    -DPLATFORM_PICO
build_src_filter = 
    +<*>
    -<core/keyboard_utils_esp32.cpp>
lib_deps =
    ArduinoJson

; =============================================
; Debug (dev)
; =============================================
[env:rpipico2w_debug]
extends = env:rpipico2w
build_flags =
    ${env:rpipico2w.build_flags}
    -D DEBUG

; ================== Pico W ===================
; =============================================
; Production (release)
; =============================================
[env:rpipicow]
extends = env:base
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower
board_build.filesystem_size = 0.5m
monitor_speed = 115200
upload_protocol = picotool
build_flags = 
    -DPLATFORM_PICO
build_src_filter = 
    +<*>
    -<core/keyboard_utils_esp32.cpp>
lib_deps =
    ArduinoJson

; =============================================
; Debug (dev)
; =============================================
[env:rpipicow_debug]
extends = env:rpipicow
build_flags =
    ${env:rpipicow.build_flags}
    -D DEBUG

; ================= ESP32-S2 ==================
; =============================================
; Production (release)
; =============================================
[env:esp32-s2-saola-1]
extends = env:base
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s2-saola-1
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
build_flags = 
    -DPLATFORM_ESP32
build_src_filter = 
    +<*>
    -<core/keyboard_utils_pico.cpp>
lib_deps =
    ArduinoJson

; =============================================
; Debug (dev)
; =============================================
[env:esp32-s2-saola-1_debug]
extends = env:esp32-s2-saola-1
build_flags =
    ${env:esp32-s2-saola-1.build_flags}
    -D DEBUG